### ISSUE TITLE
single mode fails with non-wave files

### ISSUE THREAD

**Issue by superbock** [CPJKU/madmom#447] opened 2019-08-20 09:26 UTC
### Expected behaviour

Any file should be processed correctly, no matter if in `batch` or `single` mode.

### Actual behaviour

https://github.com/CPJKU/madmom/blob/master/madmom/io/audio.py#L135 overwrites the provided `infile` with `-`, thus processing of these files fails silently.

The regression was introduced with commit 33db19b572ac9df12df2a1c3af4a2441cb4312fb

### Steps needed to reproduce the behaviour

Use a `.m4a` file in single mode and it will fail to process it.

**Comment by jpauwels** [comment] 2019-12-13 12:21
I finally cracked this, but the problem is not what's described here. It has nothing to do with single mode and is specific to MP4 containers (the same code works for all FLAC files). 

The underlying issue is that in my previous commit, I changed the behaviour of handling file objects as audio input. They used to be closed, only to be reopened later again by ffmpeg, instead of streaming them into ffmpeg as stdin. Now it turned out that this complicated behaviour avoided the problem that some MP4 files are not streamable (see Stackoverflow questions https://superuser.com/questions/479063/ffmpeg-pipe-input-error and https://stackoverflow.com/questions/57958480/ffmpeg-cant-stream-aac-files-from-stdin, test for yourself by `cat`-ing the M4A test file into `ffmpeg` on the command line vs passing it as input argument). Active mode is just one example of where the audio input is a file object, but the same problem is present in similar cases.

I submitted a new pull request that fixes this behaviour, by not streaming those MP4 files, but closing them or writing them to a temporary file if necessary.

**Closed** 2019-12-19 14:47 UTC
