### ISSUE TITLE
Cannot install with Python 3.7

### ISSUE THREAD

**Issue by RustyDev** [CPJKU/madmom#373] opened 2018-07-26 19:23 UTC
Hi, I'm having an issue installing madmom. Here's the output:

```
pip3 list
Package      Version
------------ ---------
aubio        0.4.6
audioread    2.1.6
beatport     0.0.1
certifi      2018.4.16
chardet      3.0.4
Cython       0.28.4
decorator    4.3.0
idna         2.7
joblib       0.12.1
librosa      0.5.1
llvmlite     0.24.0
nose         1.3.7
numba        0.39.0
numpy        1.15.0
pip          18.0
PyAudio      0.2.11
requests     2.19.1
resampy      0.2.1
scikit-learn 0.19.2
scipy        1.1.0
setuptools   39.2.0
six          1.11.0
urllib3      1.23
wheel        0.31.1
```

```
> pip3 install madmom

Collecting madmom
  Using cached https://files.pythonhosted.org/packages/b7/bb/b9b88d504f5ed3d87dd8a952c4feb37165a96ba1015f912cd4d6f050d75f/madmom-0.15.1.tar.gz
Requirement already satisfied: numpy>=1.8.1 in /usr/local/lib/python3.7/site-packages (from madmom) (1.15.0)
Requirement already satisfied: scipy>=0.14 in /usr/local/lib/python3.7/site-packages (from madmom) (1.1.0)
Requirement already satisfied: cython>=0.22.1 in /usr/local/lib/python3.7/site-packages (from madmom) (0.28.4)
Building wheels for collected packages: madmom
  Running setup.py bdist_wheel for madmom ... error
  Complete output from command /usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/_c/cxxgtsr92_vc0lbc958s92980000gn/T/pip-install-cczviovj/madmom/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/_c/cxxgtsr92_vc0lbc958s92980000gn/T/pip-wheel-9ugmwanc --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.14-x86_64-3.7
  creating build/lib.macosx-10.14-x86_64-3.7/madmom
  copying madmom/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/madmom
  copying madmom/processors.py -> build/lib.macosx-10.14-x86_64-3.7/madmom
  creating build/lib.macosx-10.14-x86_64-3.7/madmom/features
  copying madmom/features/beats_hmm.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/features
  copying madmom/features/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/features
  copying madmom/features/notes.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/features
  copying madmom/features/tempo.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/features
  copying madmom/features/beats.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/features
  copying madmom/features/onsets.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/features
  copying madmom/features/chords.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/features
  creating build/lib.macosx-10.14-x86_64-3.7/madmom/utils
  copying madmom/utils/midi.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/utils
  copying madmom/utils/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/utils
  creating build/lib.macosx-10.14-x86_64-3.7/madmom/models
  copying madmom/models/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/models
  creating build/lib.macosx-10.14-x86_64-3.7/madmom/audio
  copying madmom/audio/signal.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/audio
  copying madmom/audio/ffmpeg.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/audio
  copying madmom/audio/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/audio
  copying madmom/audio/stft.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/audio
  copying madmom/audio/chroma.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/audio
  copying madmom/audio/spectrogram.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/audio
  copying madmom/audio/filters.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/audio
  creating build/lib.macosx-10.14-x86_64-3.7/madmom/ml
  copying madmom/ml/gmm.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/ml
  copying madmom/ml/crf.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/ml
  copying madmom/ml/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/ml
  creating build/lib.macosx-10.14-x86_64-3.7/madmom/evaluation
  copying madmom/evaluation/alignment.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/evaluation
  copying madmom/evaluation/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/evaluation
  copying madmom/evaluation/notes.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/evaluation
  copying madmom/evaluation/tempo.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/evaluation
  copying madmom/evaluation/beats.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/evaluation
  copying madmom/evaluation/onsets.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/evaluation
  creating build/lib.macosx-10.14-x86_64-3.7/madmom/ml/nn
  copying madmom/ml/nn/activations.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/ml/nn
  copying madmom/ml/nn/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/ml/nn
  copying madmom/ml/nn/layers.py -> build/lib.macosx-10.14-x86_64-3.7/madmom/ml/nn
  copying madmom/models/LICENSE -> build/lib.macosx-10.14-x86_64-3.7/madmom/models
  copying madmom/models/README.rst -> build/lib.macosx-10.14-x86_64-3.7/madmom/models
  creating build/lib.macosx-10.14-x86_64-3.7/madmom/models/beats
  creating build/lib.macosx-10.14-x86_64-3.7/madmom/models/beats/2015
  copying madmom/models/beats/2015/beats_blstm_8.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/beats/2015
  copying madmom/models/beats/2015/beats_blstm_6.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/beats/2015
  copying madmom/models/beats/2015/beats_blstm_7.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/beats/2015
  copying madmom/models/beats/2015/beats_blstm_5.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/beats/2015
  copying madmom/models/beats/2015/beats_blstm_4.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/beats/2015
  copying madmom/models/beats/2015/beats_blstm_1.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/beats/2015
  copying madmom/models/beats/2015/beats_blstm_3.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/beats/2015
  copying madmom/models/beats/2015/beats_blstm_2.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/beats/2015
  creating build/lib.macosx-10.14-x86_64-3.7/madmom/models/beats/2016
  copying madmom/models/beats/2016/beats_lstm_1.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/beats/2016
  copying madmom/models/beats/2016/beats_lstm_3.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/beats/2016
  copying madmom/models/beats/2016/beats_lstm_2.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/beats/2016
  copying madmom/models/beats/2016/beats_lstm_6.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/beats/2016
  copying madmom/models/beats/2016/beats_lstm_7.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/beats/2016
  copying madmom/models/beats/2016/beats_lstm_5.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/beats/2016
  copying madmom/models/beats/2016/beats_lstm_4.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/beats/2016
  copying madmom/models/beats/2016/beats_lstm_8.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/beats/2016
  creating build/lib.macosx-10.14-x86_64-3.7/madmom/models/chords
  creating build/lib.macosx-10.14-x86_64-3.7/madmom/models/chords/2016
  copying madmom/models/chords/2016/chords_dccrf.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/chords/2016
  copying madmom/models/chords/2016/chords_cnncrf.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/chords/2016
  copying madmom/models/chords/2016/chords_cnnfeat.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/chords/2016
  creating build/lib.macosx-10.14-x86_64-3.7/madmom/models/chroma
  creating build/lib.macosx-10.14-x86_64-3.7/madmom/models/chroma/2016
  copying madmom/models/chroma/2016/chroma_dnn.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/chroma/2016
  creating build/lib.macosx-10.14-x86_64-3.7/madmom/models/downbeats
  creating build/lib.macosx-10.14-x86_64-3.7/madmom/models/downbeats/2016
  copying madmom/models/downbeats/2016/downbeats_blstm_8.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/downbeats/2016
  copying madmom/models/downbeats/2016/downbeats_blstm_2.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/downbeats/2016
  copying madmom/models/downbeats/2016/downbeats_blstm_3.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/downbeats/2016
  copying madmom/models/downbeats/2016/downbeats_blstm_1.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/downbeats/2016
  copying madmom/models/downbeats/2016/downbeats_blstm_4.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/downbeats/2016
  copying madmom/models/downbeats/2016/downbeats_blstm_5.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/downbeats/2016
  copying madmom/models/downbeats/2016/downbeats_blstm_7.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/downbeats/2016
  copying madmom/models/downbeats/2016/downbeats_blstm_6.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/downbeats/2016
  creating build/lib.macosx-10.14-x86_64-3.7/madmom/models/notes
  creating build/lib.macosx-10.14-x86_64-3.7/madmom/models/notes/2013
  copying madmom/models/notes/2013/notes_brnn.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/notes/2013
  creating build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets
  creating build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2013
  copying madmom/models/onsets/2013/onsets_brnn_1.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2013
  copying madmom/models/onsets/2013/onsets_brnn_2.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2013
  copying madmom/models/onsets/2013/onsets_brnn_3.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2013
  copying madmom/models/onsets/2013/onsets_brnn_7.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2013
  copying madmom/models/onsets/2013/onsets_brnn_6.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2013
  copying madmom/models/onsets/2013/onsets_brnn_4.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2013
  copying madmom/models/onsets/2013/onsets_brnn_5.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2013
  copying madmom/models/onsets/2013/onsets_rnn_8.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2013
  copying madmom/models/onsets/2013/onsets_cnn.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2013
  copying madmom/models/onsets/2013/onsets_rnn_1.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2013
  copying madmom/models/onsets/2013/onsets_rnn_2.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2013
  copying madmom/models/onsets/2013/onsets_rnn_3.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2013
  copying madmom/models/onsets/2013/onsets_rnn_7.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2013
  copying madmom/models/onsets/2013/onsets_rnn_6.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2013
  copying madmom/models/onsets/2013/onsets_rnn_4.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2013
  copying madmom/models/onsets/2013/onsets_rnn_5.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2013
  copying madmom/models/onsets/2013/onsets_brnn_8.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2013
  creating build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2014
  copying madmom/models/onsets/2014/onsets_brnn_pp_8.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2014
  copying madmom/models/onsets/2014/onsets_brnn_pp_4.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2014
  copying madmom/models/onsets/2014/onsets_brnn_pp_5.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2014
  copying madmom/models/onsets/2014/onsets_brnn_pp_7.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2014
  copying madmom/models/onsets/2014/onsets_brnn_pp_6.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2014
  copying madmom/models/onsets/2014/onsets_brnn_pp_2.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2014
  copying madmom/models/onsets/2014/onsets_brnn_pp_3.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2014
  copying madmom/models/onsets/2014/onsets_brnn_pp_1.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/onsets/2014
  creating build/lib.macosx-10.14-x86_64-3.7/madmom/models/patterns
  creating build/lib.macosx-10.14-x86_64-3.7/madmom/models/patterns/2013
  copying madmom/models/patterns/2013/ballroom_pattern_4_4.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/patterns/2013
  copying madmom/models/patterns/2013/ballroom_pattern_3_4.pkl -> build/lib.macosx-10.14-x86_64-3.7/madmom/models/patterns/2013
  running build_ext
  building 'madmom.audio.comb_filters' extension
  creating build/temp.macosx-10.14-x86_64-3.7
  creating build/temp.macosx-10.14-x86_64-3.7/madmom
  creating build/temp.macosx-10.14-x86_64-3.7/madmom/audio
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/lib/python3.7/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c madmom/audio/comb_filters.c -o build/temp.macosx-10.14-x86_64-3.7/madmom/audio/comb_filters.o
  In file included from madmom/audio/comb_filters.c:586:
  In file included from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
  In file included from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
  In file included from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1821:
  /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
  #warning "Using deprecated NumPy API, disable it by " \
   ^
  1 warning generated.
  clang -bundle -undefined dynamic_lookup build/temp.macosx-10.14-x86_64-3.7/madmom/audio/comb_filters.o -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -o build/lib.macosx-10.14-x86_64-3.7/madmom/audio/comb_filters.cpython-37m-darwin.so
  building 'madmom.features.beats_crf' extension
  creating build/temp.macosx-10.14-x86_64-3.7/madmom/features
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/lib/python3.7/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c madmom/features/beats_crf.c -o build/temp.macosx-10.14-x86_64-3.7/madmom/features/beats_crf.o
  In file included from madmom/features/beats_crf.c:587:
  In file included from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
  In file included from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
  In file included from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1821:
  /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
  #warning "Using deprecated NumPy API, disable it by " \
   ^
  1 warning generated.
  clang -bundle -undefined dynamic_lookup build/temp.macosx-10.14-x86_64-3.7/madmom/features/beats_crf.o -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -o build/lib.macosx-10.14-x86_64-3.7/madmom/features/beats_crf.cpython-37m-darwin.so
  building 'madmom.ml.hmm' extension
  creating build/temp.macosx-10.14-x86_64-3.7/madmom/ml
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/lib/python3.7/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c madmom/ml/hmm.c -o build/temp.macosx-10.14-x86_64-3.7/madmom/ml/hmm.o
  In file included from madmom/ml/hmm.c:587:
  In file included from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
  In file included from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
  In file included from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1821:
  /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
  #warning "Using deprecated NumPy API, disable it by " \
   ^
  1 warning generated.
  clang -bundle -undefined dynamic_lookup build/temp.macosx-10.14-x86_64-3.7/madmom/ml/hmm.o -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -o build/lib.macosx-10.14-x86_64-3.7/madmom/ml/hmm.cpython-37m-darwin.so
  building 'madmom.ml.nn.layers' extension
  creating build/temp.macosx-10.14-x86_64-3.7/madmom/ml/nn
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/lib/python3.7/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c madmom/ml/nn/layers.c -o build/temp.macosx-10.14-x86_64-3.7/madmom/ml/nn/layers.o
  In file included from madmom/ml/nn/layers.c:446:
  In file included from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
  In file included from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
  In file included from /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1821:
  /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
  #warning "Using deprecated NumPy API, disable it by " \
   ^
  madmom/ml/nn/layers.c:17426:65: error: too many arguments to function call, expected 3, have 4
      return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                     ^~~~
  /usr/local/Cellar/llvm/6.0.1/lib/clang/6.0.1/include/stddef.h:105:16: note: expanded from macro 'NULL'
  #  define NULL ((void*)0)
                 ^~~~~~~~~~
  madmom/ml/nn/layers.c:18807:21: error: no member named 'exc_type' in 'struct _ts'
      *type = tstate->exc_type;
              ~~~~~~  ^
  madmom/ml/nn/layers.c:18808:22: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
      *value = tstate->exc_value;
                       ^~~~~~~~~
                       curexc_value
  /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here
      PyObject *curexc_value;
                ^
  madmom/ml/nn/layers.c:18809:19: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
      *tb = tstate->exc_traceback;
                    ^~~~~~~~~~~~~
                    curexc_traceback
  /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here
      PyObject *curexc_traceback;
                ^
  madmom/ml/nn/layers.c:18816:24: error: no member named 'exc_type' in 'struct _ts'
      tmp_type = tstate->exc_type;
                 ~~~~~~  ^
  madmom/ml/nn/layers.c:18817:25: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
      tmp_value = tstate->exc_value;
                          ^~~~~~~~~
                          curexc_value
  /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here
      PyObject *curexc_value;
                ^
  madmom/ml/nn/layers.c:18818:22: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
      tmp_tb = tstate->exc_traceback;
                       ^~~~~~~~~~~~~
                       curexc_traceback
  /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here
      PyObject *curexc_traceback;
                ^
  madmom/ml/nn/layers.c:18819:13: error: no member named 'exc_type' in 'struct _ts'
      tstate->exc_type = type;
      ~~~~~~  ^
  madmom/ml/nn/layers.c:18820:13: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
      tstate->exc_value = value;
              ^~~~~~~~~
              curexc_value
  /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here
      PyObject *curexc_value;
                ^
  madmom/ml/nn/layers.c:18821:13: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
      tstate->exc_traceback = tb;
              ^~~~~~~~~~~~~
              curexc_traceback
  /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here
      PyObject *curexc_traceback;
                ^
  madmom/ml/nn/layers.c:18876:24: error: no member named 'exc_type' in 'struct _ts'
      tmp_type = tstate->exc_type;
                 ~~~~~~  ^
  madmom/ml/nn/layers.c:18877:25: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
      tmp_value = tstate->exc_value;
                          ^~~~~~~~~
                          curexc_value
  /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here
      PyObject *curexc_value;
                ^
  madmom/ml/nn/layers.c:18878:22: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
      tmp_tb = tstate->exc_traceback;
                       ^~~~~~~~~~~~~
                       curexc_traceback
  /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here
      PyObject *curexc_traceback;
                ^
  madmom/ml/nn/layers.c:18879:13: error: no member named 'exc_type' in 'struct _ts'
      tstate->exc_type = local_type;
      ~~~~~~  ^
  madmom/ml/nn/layers.c:18880:13: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
      tstate->exc_value = local_value;
              ^~~~~~~~~
              curexc_value
  /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here
      PyObject *curexc_value;
                ^
  madmom/ml/nn/layers.c:18881:13: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
      tstate->exc_traceback = local_tb;
              ^~~~~~~~~~~~~
              curexc_traceback
  /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here
      PyObject *curexc_traceback;
                ^
  1 warning and 16 errors generated.
  error: command 'clang' failed with exit status 1

  ----------------------------------------
  Failed building wheel for madmom

**Comment by superbock** [comment] 2018-07-26 19:30
I'll have to dig into that. I might be a problem with Python 3.7 which hasn't been tested automatically yet. Could you try with Python 2.7 or 3.6 instead to rule this out?

If you can't install another Python version, you could also delete `madmom/ml/nn/layers.pxd` file. Then this file won't be cythonised, but it will still work, since this is only there for speed reasons.

**Comment by superbock** [comment] 2018-07-27 05:06
Ok, we have to check Python 3.7 compatibility.

**Comment by superbock** [comment] 2018-10-18 10:37
Hi, I added Python 3.7 to the CI builds (#374). However, it does not fail and installs just fine.

I also tried locally on my Mac OS machine and can't reproduce it there likewise. However, I am on an older version (10.12) and use macports. It seems that you are using homebrew, right?

Can you please check if this problem still persists or if it is solved by the changes committed to the other branch. I am not sure if the changes made in `layers.py` affect this problem or not.

**Comment by declension** [comment] 2018-11-27 09:48
Note https://github.com/cython/cython/issues/1955, which seems to be a root cause of a lot of these types of errors.  Looking through that tangle of partial fixes led me to https://github.com/cython/cython/pull/2607 - which looks like it made it into [release 0.29](https://github.com/cython/cython/releases/tag/0.29).

@RustyDev therefore given you state you were on `Cython       0.28.4`, perhaps an upgrade to the [latest brew cython](https://formulae.brew.sh/formula/cython) (currently `0.29.1`) might fix this?

**Comment by superbock** [comment] 2018-11-28 15:57
Actually this might indeed be the root of the problem. On top of that there was a time when packages on PyPI did not contain the .pyx files and came only with .c files. If those were generated with an older version of cython this could lead to these errors.

@RustyDev, could you please try again with the current PyPI version of madmom (v0.16.1) and if the error still persists, update cython to see if this solves the issue?

**Comment by Laubeee** [comment] 2019-03-26 09:24
fyi: I just built it successfully on Windows (Python 3.7.2) using:
numpy 1.15.4
scipy 1.2.1
cython 0.28.2
mido 1.2.9

**Comment by superbock** [comment] 2019-03-26 16:18
Thanks for sharing this information. Since I don't use Windows I can not investigate this further and will close this issue since it worked at least for someone. Please feel free to add more information to this issue if available.

**Closed by superbock** 2019-03-26 16:18 UTC
