### ISSUE TITLE
 Spectrogram check bug in HarmonicPitchClassProfile ?

### ISSUE THREAD

**Issue by www10177** [CPJKU/madmom#291] opened 2017-05-24 18:29 UTC
in [line 162](https://github.com/CPJKU/madmom/blob/master/madmom/audio/chroma.py#L162), do a check to ensure Spectrogram do not be filtered.  
` if spectrogram.filterbank is not None:`
However, if spectrogram was not filtered, it didn't own any attribute named filterbank  

it would show error  AttributeError: 'Spectrogram' object has no attribute 'filterbank'
`framedSig=madmom.audio.signal.FramedSignal(filename, num_channels=1)     `
`spec=madmom.audio.spectrogram.Spectrogram(framedSig)  `
`cho=madmom.audio.chroma.HarmonicPitchClassProfile  `

I thought it should change  
 `spectrogram.filterbank is not None` to  `hasattr(spectrogram, 'filterbank')`  
Is it right? Or I misunderstood this ?

**Comment by superbock** [comment] 2017-05-24 19:08
Yes, you're right. This is actually a duplicate of #272 and will be fixed soon. I intended to merge #281 together with a solution for #87, but will probably merge it nonetheless.

**Closed** 2017-06-01 11:27 UTC
