### ISSUE TITLE
TypeError: read() got an unexpected keyword argument 'mmap'

### ISSUE THREAD

**Issue by jseales** [CPJKU/madmom#323] opened 2017-08-11 21:46 UTC
Hey folks - looks like you edited signal.py in the last day, and maybe this is broken? Here's the full error spew:

File "autoTR2017.py", line 92, in getTonerows
    chroma = madmom.audio.chroma.DeepChromaProcessor()(soundFileHandle)
  File "/Library/Python/2.7/site-packages/madmom/processors.py", line 128, in __call__
    return self.process(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/madmom/processors.py", line 336, in process
    data = _process((processor, data, kwargs))
  File "/Library/Python/2.7/site-packages/madmom/processors.py", line 200, in _process
    return process_tuple[0](*process_tuple[1:-1], **process_tuple[-1])
  File "/Library/Python/2.7/site-packages/madmom/processors.py", line 128, in __call__
    return self.process(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/madmom/audio/signal.py", line 909, in process
    return Signal(data, **args)
  File "/Library/Python/2.7/site-packages/madmom/audio/signal.py", line 743, in __new__
    dtype=dtype)
  File "/Library/Python/2.7/site-packages/madmom/audio/signal.py", line 610, in load_audio_file
    stop=stop, dtype=dtype)
  File "/Library/Python/2.7/site-packages/madmom/audio/signal.py", line 496, in load_wave_file
    file_sample_rate, signal = wavfile.read(filename, mmap=True)
TypeError: read() got an unexpected keyword argument 'mmap'

ps. Madmom is awesome! The NN Chroma is far cleaner than what I used to use.  Thank you!!!

**Comment by superbock** [comment] 2017-08-11 22:13
I think this is unrelated to the yesterday's change in `signal.py`.

The error is raised by `wavfile.read` and says that it doesn't support the `mmap` argument. By any chance, did this happen on a system which has an old version of scipy? [Their docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.wavfile.read.html#scipy.io.wavfile.read) say that this argument it was added in version 0.12 (released May 2013). madmom supports only scipy > 0.16.

**Comment by jseales** [comment] 2017-08-28 05:25
Scipy version is 0.19. 

Any other ideas what the problem might be?

**Comment by superbock** [comment] 2017-08-28 09:00
Unfortunately no. But to narrow it down, you can check out an earlier commit (e.g. dfa6c1ce) to confirm that it works without the last changes to `signal.py`. If that works we have to investigate further.

Another thing to look at is that there is no older SciPy version around which is used when invoking your script. To check that you could add a simple `print(scipy.__version__)` just before the offending line in `signal.py`.

**Comment by superbock** [comment] 2017-10-15 05:02
@jseales any updates regarding this issue? Otherwise I'll close it since I am not able to reproduce it.

**Closed** 2017-12-25 11:22 UTC
