### ISSUE TITLE
Site is broken

### ISSUE THREAD

**Issue by sharfiky** [CPJKU/madmom#360] opened 2018-04-05 18:31 UTC
Your last commit IO broke the site for example I have no information about features.onset

**Comment by superbock** [comment] 2018-04-05 19:28
That's weird, since none of the new commits should have triggered this problem, and I can't reproduce the problem locally. I fixed one warning causing a malformed docstring in #361, but this is unrelated to this problem.

I fear your best bet is to use some older (probably outdated) docs, e.g. http://madmom.readthedocs.io/en/v0.15/modules/features/onsets.html

**Comment by superbock** [comment] 2018-04-05 19:40
Got it: f2e8d18. Docs should works soon again. Thanks for reporting it!

**Closed** 2018-04-05 19:53 UTC
